title: Rubén Castillo Sánchez
logo: /assets/img/logo.png
description: Quantitative analyst focused on applying AI, ML, and algorithmic techniques to financial markets. Passionate about investing, solving challenges, and the automation of complex and abstract tasks..
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal